#  Template maven-build

#  This template allows you to test and build your Java project with Maven.
#  The workflow allows running tests, code checkstyle and security scans on the default branch.

# Prerequisites: pom.xml and appropriate project structure should exist in the repository.

image:
  name: elementalcomputing/elements-web-services-ci:478258e2ae2e0372f61dced6d0050af648b8b8ac
  username: $DOCKER_HUB_USER
  password: $DOCKER_HUB_ACCESS_TOKEN

definitions:
  services:
    docker:
      # In spite of what IntelliJ says, this must be here to support
      # the buildx commands properly
      image: docker:dind

options:
  max-time: 60
  docker: true
  size: 2x

pipelines:
  tags:
    "*":
      - step:
          size: 4x
          name: Build Tags
          runs-on:
            - "linux"
            - "self.hosted"
          script:
            - make setup
            - make build
            - make docker docker_hub
            - make push_tags publish_github_tags
          after-script:
            # Collect checkstyle results, if any, and convert to Bitbucket Code Insights.
            - pipe: atlassian/checkstyle-report:0.3.0
  branches:
    "release/*":
      - step:
          size: 4x
          name: Build and Test - Release
          runs-on:
            - "linux"
            - "self.hosted"
          script:
            - make setup
            - make detach tag
            - make BRANCH=$BITBUCKET_BRANCH checkout
            - make release
            - make COMMIT_MSG="[ci skip] Setting Next Version:" commit
            - make push push_tags publish_github publish_github_tags
          after-script:
            # Collect checkstyle results, if any, and convert to Bitbucket Code Insights.
            - pipe: atlassian/checkstyle-report:0.3.0
    "development/*":
      - step:
          size: 4x
          name: Build and Test - Development
          runs-on:
            - "linux"
            - "self.hosted"
          script:
            - make setup
            - make detach tag
            - make BRANCH=$BITBUCKET_BRANCH checkout
            - make patch
            - make COMMIT_MSG="[ci skip] Setting Next Version:" commit
            - make push push_tags publish_github publish_github_tags
          after-script:
            # Collect checkstyle results, if any, and convert to Bitbucket Code Insights.
            - pipe: atlassian/checkstyle-report:0.3.0
    main:
      - step:
          size: 4x
          name: Build and Test
          runs-on:
            - "linux"
            - "self.hosted"
          caches:
            - maven
          script:
            - make setup
            - make build
            - make docker
            - make publish_github
          after-script:
            # Collect checkstyle results, if any, and convert to Bitbucket Code Insights.
            - pipe: atlassian/checkstyle-report:0.3.0
  default:
    - step:
        size: 4x
        name: Build and Test
        runs-on:
          - "linux"
          - "self.hosted"
        caches:
          - maven
        script:
          - make setup
          - make build
          - make docker
        after-script:
          # Collect checkstyle results, if any, and convert to Bitbucket Code Insights.
          - pipe: atlassian/checkstyle-report:0.3.0
